# Generated by Django 5.1.7 on 2025-06-19 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_category_options_alter_source_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('daily_spend', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10), blank=True, default=list, size=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
