# Generated by Django 5.1.7 on 2026-01-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='total_budget',
        ),
        migrations.RemoveField(
            model_name='month',
            name='total_remaining',
        ),
        migrations.AddField(
            model_name='source',
            name='annual_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='source',
            name='reward_type',
            field=models.CharField(choices=[('cashback', 'Cashback'), ('points', 'Points'), ('miles', 'Miles')], default='cashback', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.source'),
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.source')),
            ],
            options={
                'ordering': ['source__name', 'category__name'],
            },
        ),
    ]
