# Generated by Django 5.1.7 on 2026-01-20 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_month_total_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reporting_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_children', to='tracker.category'),
        ),
    ]
