# Generated by Django 5.1.7 on 2026-01-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_month_total_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='reward_type',
            field=models.CharField(choices=[('cashback', 'Cashback'), ('none', 'None'), ('miles', 'Miles')], default='cashback', max_length=100),
        ),
    ]
