# Generated by Django 5.1.7 on 2026-01-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_source_reward_type'),
        ('tracker', '0007_category_reporting_category'),
    ]

    operations = [
    ]
