# Generated by Django 5.1.7 on 2026-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_merge_20260120_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcategory',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardcategory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
