# Generated by Django 5.1.7 on 2026-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_rewardcategory_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardcategory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rewardcategory',
            name='start_date',
        ),
        migrations.AddField(
            model_name='rewardcategory',
            name='applicable_quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
