# Generated by Django 5.1.7 on 2026-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rewardcategory_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reimbursement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
