# Generated by Django 5.1.7 on 2026-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_source_reward_type_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DismissedSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-dismissed_at'],
            },
        ),
    ]
