# Generated by Django 5.1.7 on 2026-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_dismissedsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
