# Generated by Django 5.1.7 on 2026-03-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_savingsgoal_goalcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='closed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
